### ISSUE TITLE
cgroup2 support is now available upstream

### ISSUE THREAD

**Issue by snehring** [plazonic/cgroup_exporter#1]
Hello!

https://github.com/treydock/cgroup_exporter/tree/v1.0.0-rc.0 was cut today and adds cgroupv2 support 

Any chance you can sync up so that cgroupv2 cgroups will be available with this?

**Comment by plazonic** [comment]
Hullo,

have you checked cgroupv2 branch? I sort of gave up on treydock's way of doing things (as containerd/cgroups/v3 did not support some of the required stats) and instead went for direct parsing of needed data. It is simpler and probably faster.

In my limited testing it seemed to work but our RHEL9 based cluster has been delayed so we have not had opportunity to test this better. We will get back to it soon, even if only in smaller testing (1 node cluster, test deployment) but would appreciate any comments if you could give it a try.

Thanks.

**Comment by snehring** [comment]
Sure, I can test it.

**Comment by snehring** [comment]
It does seem to be gathering metrics for cgroups on our rhel9 test cluster without any obvious sign of error.

**Comment by plazonic** [comment]
Wonderful. I guess I'll close this issue but *please* open new ones if you discover any issues with this version. Your testing of this is very much appreciated.
