### ISSUE TITLE
cgroup v2 is not supported yet, right?

### ISSUE THREAD

**Issue by astappiev** [plazonic/cgroup_exporter#4]

**Comment by plazonic** [comment]
It is - please check the cgroupv2 branch:

https://github.com/plazonic/cgroup_exporter/tree/cgroupv2

We are using it in production.

**Comment by astappiev** [comment]
I haven't seen that.

Thank you very much, now trying it and it seems to work!

It would be nice to include it in README.
Also, `--config.paths` doesn't exist there, should be removed from README in that version.
